# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=500)),
                ('regards', models.CharField(choices=[('Real Estate', 'Real Estate'), ('Mortgage', 'Mortgage'), ('Event Hall', 'Event Hall')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HomeListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('description', models.TextField(max_length=500)),
                ('sqft', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('picture1', models.ImageField(upload_to='images/')),
                ('picture2', models.ImageField(upload_to='images/')),
                ('picture3', models.ImageField(upload_to='images/')),
                ('picture4', models.ImageField(upload_to='images/')),
                ('picture5', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
